# Generated by Django 6.1.1 on 2026-09-18 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
