# Generated by Django 6.1.1 on 2026-09-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='day',
            field=models.CharField(max_length=15),
        ),
    ]
