# Generated by Django 6.1.1 on 2026-09-15 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_auditlog_notificationalert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='symptoms',
            new_name='chief_complaint',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='created_at',
            new_name='consultation_date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='instructions',
        ),
        migrations.AddField(
            model_name='consultation',
            name='clinical_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='clinical.consultation'),
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], default='O+', max_length=5)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('allergies', models.TextField(blank=True, default='None reported')),
                ('chronic_conditions', models.TextField(blank=True, default='None')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='clinical.patient')),
            ],
        ),
    ]
