# Generated by Django 6.1.1 on 2026-09-15 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_rename_symptoms_consultation_chief_complaint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor_id',
            field=models.CharField(db_index=True, default='12345', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='doctor_id',
            field=models.CharField(db_index=True, default='12345', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor_id',
            field=models.CharField(db_index=True, default='12345', max_length=20),
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('clinical_email', models.EmailField(max_length=254)),
                ('specialization', models.CharField(default='General Practice', max_length=100)),
                ('department', models.CharField(default='Clinical Outpatient', max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
