# Generated by Django 6.1.1 on 2026-09-16 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_prescription_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='locked_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='queue_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Waiting', 'Waiting'), ('In-Consultation', 'In-Consultation'), ('Completed', 'Completed')], default='Scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='client_ip',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='endpoint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pdf_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='VitalsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('blood_pressure', models.CharField(default='120/80', max_length=20)),
                ('systolic', models.IntegerField(default=120)),
                ('diastolic', models.IntegerField(default=80)),
                ('heart_rate', models.IntegerField(default=72)),
                ('oxygen_saturation', models.IntegerField(default=98)),
                ('temperature', models.DecimalField(decimal_places=1, default=98.6, max_digits=4)),
                ('respiratory_rate', models.IntegerField(default=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='clinical.patient')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
