# Generated by Django 6.1.1 on 2026-09-18 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_appointmentslot_is_locked_appointmentslot_locked_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='queue_status',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='client_ip',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pdf_url',
        ),
        migrations.DeleteModel(
            name='VitalsLog',
        ),
    ]
